version: '3'

services:
  telegram_news:
    build: .
    container_name: telegram_news
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}
    ports:
      - 7878:7878